/**
 * PDF Builder using Puppeteer
 * Converts HTML to professional PDF documents
 */

import puppeteer, { Browser, PDFOptions as PuppeteerPDFOptions } from 'puppeteer';

export interface PDFOptions {
  format?: 'A4' | 'Letter' | 'Legal';
  landscape?: boolean;
  margin?: {
    top?: string;
    right?: string;
    bottom?: string;
    left?: string;
  };
  displayHeaderFooter?: boolean;
  headerTemplate?: string;
  footerTemplate?: string;
  printBackground?: boolean;
  scale?: number;
}

const DEFAULT_OPTIONS: PDFOptions = {
  format: 'A4',
  landscape: false,
  margin: {
    top: '20mm',
    right: '15mm',
    bottom: '20mm',
    left: '15mm',
  },
  displayHeaderFooter: true,
  headerTemplate: `
    <div style="font-size: 10px; width: 100%; text-align: center; color: #666;">
      <span class="title"></span>
    </div>
  `,
  footerTemplate: `
    <div style="font-size: 10px; width: 100%; text-align: center; color: #666;">
      Page <span class="pageNumber"></span> of <span class="totalPages"></span>
    </div>
  `,
  printBackground: true,
  scale: 1,
};

export class PDFBuilder {
  private browser: Browser | null = null;

  /**
   * Get or create browser instance (lazy loading)
   */
  private async getBrowser(): Promise<Browser> {
    if (!this.browser) {
      this.browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
      });
    }
    return this.browser;
  }

  /**
   * Generate PDF from HTML string
   */
  async generatePDF(html: string, outputPath: string): Promise<void> {
    await this.generatePDFWithOptions(html, outputPath, DEFAULT_OPTIONS);
  }

  /**
   * Generate PDF with custom options
   */
  async generatePDFWithOptions(
    html: string,
    outputPath: string,
    options: PDFOptions
  ): Promise<void> {
    const browser = await this.getBrowser();
    const page = await browser.newPage();

    try {
      // Set content and wait for styles to load
      await page.setContent(html, { waitUntil: 'networkidle0' });

      // Generate PDF
      const pdfOptions: PuppeteerPDFOptions = {
        path: outputPath,
        format: options.format || 'A4',
        landscape: options.landscape || false,
        margin: options.margin || DEFAULT_OPTIONS.margin,
        displayHeaderFooter: options.displayHeaderFooter ?? true,
        headerTemplate: options.headerTemplate || DEFAULT_OPTIONS.headerTemplate,
        footerTemplate: options.footerTemplate || DEFAULT_OPTIONS.footerTemplate,
        printBackground: options.printBackground ?? true,
        scale: options.scale || 1,
      };

      await page.pdf(pdfOptions);
    } finally {
      await page.close();
    }
  }

  /**
   * Generate PDF with executive summary optimized settings
   */
  async generateExecutivePDF(html: string, outputPath: string): Promise<void> {
    await this.generatePDFWithOptions(html, outputPath, {
      ...DEFAULT_OPTIONS,
      format: 'A4',
      margin: {
        top: '25mm',
        right: '20mm',
        bottom: '25mm',
        left: '20mm',
      },
      headerTemplate: `
        <div style="font-size: 9px; width: 100%; padding: 0 20mm; display: flex; justify-content: space-between; color: #666;">
          <span>Technical Due Diligence Report</span>
          <span>CONFIDENTIAL</span>
        </div>
      `,
      footerTemplate: `
        <div style="font-size: 9px; width: 100%; padding: 0 20mm; display: flex; justify-content: space-between; color: #666;">
          <span>Generated by lean-intel</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `,
    });
  }

  /**
   * Generate PDF with full analysis optimized settings
   */
  async generateFullAnalysisPDF(html: string, outputPath: string): Promise<void> {
    await this.generatePDFWithOptions(html, outputPath, {
      ...DEFAULT_OPTIONS,
      format: 'A4',
      margin: {
        top: '20mm',
        right: '15mm',
        bottom: '20mm',
        left: '15mm',
      },
    });
  }

  /**
   * Check if PDF generation is available
   */
  async isAvailable(): Promise<boolean> {
    try {
      const browser = await this.getBrowser();
      return !!browser;
    } catch {
      return false;
    }
  }

  /**
   * Close browser instance
   */
  async close(): Promise<void> {
    if (this.browser) {
      await this.browser.close();
      this.browser = null;
    }
  }
}
